Add version check for pubspec.yaml in publish workflow

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,6 +1,9 @@
 name: Github Release
 
 on:
+  pull_request:
+    branches:
+      - main
   push:
     branches:
       - main
@@ -12,7 +15,18 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v4      
+      
+      - name: Check if pubspec.yaml version was increased
+        if: github.event_name == 'pull_request'
+        run: |
+          git fetch origin main:main
+          PREVIOUS_VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //')
+          PREVIOUS_VERSION_MAIN=$(git show main:pubspec.yaml | grep '^version:' | sed 's/version: //')
+          if [ "$PREVIOUS_VERSION" == "$PREVIOUS_VERSION_MAIN" ]; then
+            echo "Version was not increased. Failing the workflow."
+            exit 1
+          fi
 
       - name: Setup Flutter
         uses: subosito/flutter-action@v2
